### ISSUE TITLE
Transparency mode

### ISSUE THREAD

**Issue by EKE00372** [greven/oUF_Lumen#11]
hello greven (neverg?), do you interested transparency mode?

trans UF bar and color smooth on background/loss

**Comment by greven** [comment]
That is styling, which you will need to add it yourself, sorry.
This is the style I implemented and it is how I like it, it might change over time of course.
It shouldn't be too hard to do, but you would need to go over each frame and change the backdrop alpha basically. Looks cool, to be honest, but just not my cup of tea.

Thanks for the suggestion though! :)
