### ISSUE TITLE
Error when loading

### ISSUE THREAD

**Issue by csamolot** [greven/oUF_Lumen#13]
I get this error when loading the UI

Message: Deferred XML Node object named oUF_ClickCastUnitTemplate already exists
Time: Sun Dec  2 17:26:42 2018
Count: 5

I'm using Lumen version 8.0.9. I've tried version 8.0.10 and I still get the error but then I'm unable to move the frames.

**Comment by greven** [comment]
Sorry for never replying to this, but this was in a period I wasn't playing.
It is related to this: https://www.wowinterface.com/forums/showthread.php?t=56409

Never experienced it. If you do still experience or still use the addon do say.
It is not an easy fix it seems. Related to Blizzard way of doing things.
