### ISSUE TITLE
Move fonts to configuration

### ISSUE THREAD

**Issue by aldfiar** [greven/oUF_Lumen#15]
Hello!
In both your projects (LumUI and oUF_Lumen) fonts defined in Globals/Media section. So, if someone wants to override them, basic way is to replace fonts in media folder. 
If you doesn't have enought time for this feature, i can create merge request with changes in both projects

**Comment by greven** [comment]
Hi that is a good idea. Worry not I'll do it quickly.

**Comment by greven** [comment]
Done: https://github.com/greven/oUF_Lumen/commit/8edcdd861ec2615ebdbc22da03b80d1ce04a3b4b

Will come on the next release (WoW Interface or Github releases).

Thanks for suggesting this.
