### ISSUE TITLE
Weird frame

### ISSUE THREAD

**Issue by GnafFr** [greven/oUF_lumen#6]
I play a rogue...

Addon:
- TidyPlate_ThreatPlate (need to be disabled)
- Molinary
- sct
- tulla_range
- oUF_lumen

![wowscrnshot_072018_195046](https://user-images.githubusercontent.com/41486546/43017443-77c95682-8c56-11e8-83a9-f8400a9d0ba8.jpg)
![wowscrnshot_072018_195053](https://user-images.githubusercontent.com/41486546/43017540-c75e66d8-8c56-11e8-873d-9c148b01391d.jpg)
![wowscrnshot_072018_195108](https://user-images.githubusercontent.com/41486546/43017545-ca2c38ea-8c56-11e8-9a0d-02f097858161.jpg)

and in Game

![wowscrnshot_072018_194728](https://user-images.githubusercontent.com/41486546/43017580-e94b8564-8c56-11e8-9487-4a2b074c9c03.jpg)

**Comment by greven** [comment]
Have you downloaded the latest version from WoWInterface?
Will fix that: https://www.wowinterface.com/downloads/info16885-oUF_lumen.html
